const data = [
    {
        id: 1,
        first_name: "John",
        last_name: "Doe",
        email: "john@example.com",
        phone: "1234567890",
        city: "Habana",
        location: "Cuba",
        proffesion: "Frontend Developer",
        hobbies: ["futbol", "basket", "tennis"],
        status: true,
        avatar: "https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2371&q=80"
    },
    {
        id: 2,
        first_name: "Jane",
        last_name: "Doe",
        email: "jane@example.com",
        phone: "3434343434",
        city: "New York",
        location: "USA",
        proffesion: "Backend Developer",
        hobbies: ["Chess", "Reading", "Coding"],
        status: true,
        avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=987&q=80"
    },
    {
        id: 3,
        first_name: "Mila",
        last_name: "Kunis",
        email: "mila@example.com",
        phone: "52343434890",
        city: "Toronto",
        location: "Canada",
        proffesion: "Fullstack Developer",
        hobbies: ["Cooking", "Running", "Painting"],
        status: false,
        avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1364&q=80"
    },
    {
        id: 4,
        first_name: "Sheguro",
        last_name: "Maru",
        email: "igor@example.com",
        phone: "12349686890",
        city: "Tokyo",
        location: "Japan",
        proffesion: "Musician",
        hobbies: ["Singing", "Dancing", "Playing"],
        status: true,
        avatar: "https://images.unsplash.com/photo-1579974092487-436f30ad44d5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2370&q=80"
    },
    {
        id: 5,
        first_name: "Pablo",
        last_name: "Picasso",
        email: "picasso@example.com",
        phone: "5342347890",
        city: "Malaga",
        location: "Spain",
        proffesion: "Painter",
        hobbies: ["Painting", "Drawing", "Sculpting"],
        status: false,
        avatar: "https://images.unsplash.com/photo-1644526284291-d896f208555e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2274&q=80"
    },
    {
        id: 6,
        first_name: "Donatello",
        last_name: "Doni",
        email: "doni@example.com",
        phone: "1245567890",
        city: "Florence",
        location: "Italy",
        proffesion: "Sculptor",
        hobbies: ["Sculpting", "Painting", "Drawing"],
        status: false,
        avatar: "https://www.donatello.net/images/donatello.jpeg"
    },
    {
        id: 7,
        first_name: "Leonardo",
        last_name: "Da Vinci",
        email: "leo@example.com",
        phone: "12345634590",
        city: "Anchiano",
        location: "Italy",
        proffesion: "Painter, Sculptor, Architect, Engineer",
        hobbies: ["Painting", "Drawing", "Biology"],
        status: true,
        avatar: "https://cdn.britannica.com/06/200006-131-ABB681CF/Leonardo-da-Vinci-Italian-Renaissance-Florence-Engraving-1500.jpg"
    },
    {
        id: 8,
        first_name: "Michelangelo",
        last_name: "Buonarroti",
        email: "migue@example.com",
        phone: "12354590",
        city: "Caprese",
        location: "Italy",
        proffesion: "Painter",
        hobbies: ["Painting", "Sculpting", "Drawing"],
        status: false,
        avatar: "https://i.pinimg.com/1200x/51/3a/0f/513a0f8ff051f3d6d86b1b611ddc0b23.jpg"
    },
    {
        id: 9,
        first_name: "Julio",
        last_name: "Cortazar",
        email: "julio@example.com",
        phone: "1234564560",
        city: "Ixelles",
        location: "Belgium",
        proffesion: "Writer",
        hobbies: ["Writing", "Reading", "Drawing"],
        status: true,
        avatar: "https://imagenes.elpais.com/resizer/qo8Mrq9G3gbBKvSDJuDRB8MwJ7c=/414x0/cloudfront-eu-central-1.images.arcpublishing.com/prisa/CXI6RAZ54SEWAM7ZQTOTFJL7NI.jpg"
    },
    {
        id: 10,
        first_name: "Gabriel",
        last_name: "Garcia Marquez",
        email: "gabi@example.com",
        phone: "34456657567",
        city: "Aracataca",
        location: "Colombia",
        proffesion: "Writer",
        hobbies: ["Writing", "Reading", "Sports"],
        status: true,
        avatar: "https://i0.wp.com/radicalreads.com/wp-content/uploads/2019/07/gabriel-garcia-marquez.jpg?resize=864%2C530&ssl=1"
    },
    {
        id: 11,
        first_name: "Zeus",
        last_name: "Jupiter",
        email: "zeus@example.com",
        phone: "122354345",
        city: "First Cloud",
        location: "Olympus",
        proffesion: "God",
        hobbies: ["Thunder", "Lightning", "Thunderbolt"],
        status: true,
        avatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Zeus_Otricoli_Pio-Clementino_Inv257.jpg/800px-Zeus_Otricoli_Pio-Clementino_Inv257.jpg"
    },
    {
        id: 12,
        first_name: "Hades",
        last_name: "Inframundo",
        email: "hades@example.com",
        phone: "2345345345",
        city: "Underworld",
        location: "Hadestown",
        proffesion: "Evil God",
        hobbies: ["Evil", "Darkness", "Death"],
        status: false,
        avatar: "https://static.wikia.nocookie.net/disney/images/2/2c/Profile_-_Hades.jpeg"
    },
   
]


export default data